// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package models

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Email struct {
	ID        uuid.UUID          `json:"id"`
	MessageID string             `json:"message_id"`
	FromEmail string             `json:"from_email"`
	ToEmail   string             `json:"to_email"`
	Subject   string             `json:"subject"`
	Content   string             `json:"content"`
	SentFor   string             `json:"sent_for"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Version   int32              `json:"version"`
}

type SchemaMigration struct {
	Version int64 `json:"version"`
	Dirty   bool  `json:"dirty"`
}
