// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package models

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateEmail(ctx context.Context, arg CreateEmailParams) (Email, error)
	GetEmailByID(ctx context.Context, id uuid.UUID) (GetEmailByIDRow, error)
}

var _ Querier = (*Queries)(nil)
